version: '3.8'

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - '8080:8000'

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - '3000:8501'