version: '3.8'

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    ports:
      - "8501:8501"